name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Compile for Windows, Mac and Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o output/pbtools-${{ github.ref }}-linux-amd64
        GOOS=darwin GOARCH=arm64 go build -o output/pbtools-${{ github.ref }}-darwin-arm64
        GOOS=windows GOARCH=amd64 go build -o output/pbtools-${{ github.ref }}-windows-amd64

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          output/pbtools-${{ github.ref }}-linux-amd64
          output/pbtools-${{ github.ref }}-darwin-arm64
          output/pbtools-${{ github.ref }}-windows-amd64
